#!/bin/sh
export SCRIPTPATH

SCRIPTPATH="$(dirname "$(readlink -f "$0")")"

# Down the last running theme
[ -f "/tmp/leftwm-theme-down" ] && /tmp/leftwm-theme-down && rm /tmp/leftwm-theme-down
ln -s "$SCRIPTPATH/down" "/tmp/leftwm-theme-down"

pgrep -x "picom" && pkill picom
nohup picom --config "$SCRIPTPATH"/picom/picom.conf > /dev/null 2>&1 &

#set background using the wallpaper script
if [ -d "$SCRIPTPATH"/wallpapers ]; then
    pgrep -x "wallpaper" && pkill wallpaper
    nohup "$SCRIPTPATH"/scripts/wallpaper > /dev/null 2>&1 &
else
    feh --bg-scale "$SCRIPTPATH"/background.jpeg > /dev/null 2>&1 &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# ====[ AUTOSTART ] ====
# Start custom power management notifications
pgrep -x "battery-notify" && pkill battery-notify
nohup "$SCRIPTPATH"/scripts/battery-notify >/dev/null 2>&1 &

# ==== [ BAR CONFIGURATIONS ] ====
pkill polybar;
polybar

# ==== [ SCREEN CONFIGURATIONS ] ====
xset s 120 5
xss-lock -l -- i3lock-fancy -p
